// <auto-generated />
using DTuriasData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DTuriasData.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20170822081438_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DTuriasCore.Models.Place", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("CountryCode");

                    b.Property<string>("FullName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("DTuriasCore.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("DTuriasCore.Models.Tweet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Captured");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("FavoriteCount");

                    b.Property<string>("Language");

                    b.Property<long?>("PlaceId");

                    b.Property<bool>("PossiblySensitive");

                    b.Property<int>("RetweetCount");

                    b.Property<string>("Text");

                    b.Property<string>("Url");

                    b.Property<long?>("User");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("User");

                    b.ToTable("Tweets");
                });

            modelBuilder.Entity("DTuriasCore.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("ScreenName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DTuriasCore.Models.Tweet", b =>
                {
                    b.HasOne("DTuriasCore.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");

                    b.HasOne("DTuriasCore.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("User");
                });
#pragma warning restore 612, 618
        }
    }
}
